import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';
import { colors } from './tokens';

export const lightTheme = {
    ...MD3LightTheme,
    colors: {
        ...MD3LightTheme.colors,
        primary: colors.primary,
        primaryContainer: colors.primaryContainer,
        onPrimary: colors.onPrimary,
        onPrimaryContainer: colors.onPrimaryContainer,
        secondary: colors.secondary,
        secondaryContainer: colors.secondaryContainer,
        onSecondary: colors.onSecondary,
        onSecondaryContainer: colors.onSecondaryContainer,
        tertiary: colors.tertiary,
        tertiaryContainer: colors.tertiaryContainer,
        onTertiary: colors.onTertiary,
        onTertiaryContainer: colors.onTertiaryContainer,
        background: colors.background,
        onBackground: colors.onBackground,
        surface: colors.surface,
        onSurface: colors.onSurface,
        surfaceVariant: colors.surfaceVariant,
        onSurfaceVariant: colors.onSurfaceVariant,
        outline: colors.outline,
        outlineVariant: colors.outlineVariant,
        shadow: colors.shadow,
        scrim: colors.scrim,
    },
};

export const darkTheme = {
    ...MD3DarkTheme,
    colors: {
        ...MD3DarkTheme.colors,
        primary: colors.primary,
        primaryContainer: colors.onPrimaryContainer,
        onPrimary: colors.onPrimary,
        onPrimaryContainer: colors.primaryContainer,
        secondary: colors.secondary,
        secondaryContainer: colors.onSecondaryContainer,
        onSecondary: colors.onSecondary,
        onSecondaryContainer: colors.secondaryContainer,
        tertiary: colors.tertiary,
        tertiaryContainer: colors.onTertiaryContainer,
        onTertiary: colors.onTertiary,
        onTertiaryContainer: colors.tertiaryContainer,
        background: colors.dark.background,
        onBackground: colors.dark.onBackground,
        surface: colors.dark.surface,
        onSurface: colors.dark.onSurface,
        surfaceVariant: colors.dark.surfaceVariant,
        onSurfaceVariant: colors.dark.onSurfaceVariant,
        outline: colors.dark.outline,
        outlineVariant: colors.dark.outlineVariant,
        shadow: colors.shadow,
        scrim: colors.scrim,
    },
};
